config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reservations
  resources :room_images
  resources :reviews
  resources :rooms
  post "/users" => "users#create"
  get "/signup" => "users#new"
  post "/users" => "users#create"
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation
  validates :reservation_id, presence: true
  validates :rating, presence: true
   validates :comment, presence: true, length: { minimum: 10 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations
  has_many :room_images
  belongs_to :user
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room
  validates_format_of :url, :with => %r{\.(png|jpg|jpeg|gif)$}i, :message => "image must be png, jpg, or jpeg", multiline: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :rooms
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authenticate_user
    redirect_to '/login', status: :see_other unless current_user
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user

  def index
    @reservations = Reservation.all

    render :index
  end

  def show
    @reservation = current_user.reservations.find_by(id: params["id"])

    render :show
  end

  def new 
    @reservation = Reservation.new
    render :new
  end

  def create
    @reservation = Reservation.create(
      user_id: current_user.id,
      room_id: current_user.room.id,
      start_date: params["start_date"],
      end_date: params["end_date"],
      price: current_user.room.price,
    )

    render :show
  end

  def update
    @reservation = Reservation.find_by(id: params["id"])
    @reservation.update(
      start_date: params["start_date"] || @reservation.start_date,
      end_date: params["end_date"] || @reservation.end_date,
      price: params["price"] || @reservation.price,
    )
    if @reservation.valid?
      render :show
    else
      render json: { errors: @reservation.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    reservation = Reservation.find_by(id: params["id"])
    reservation.destroy

    render json: { message: "Reservation destroyed successfully" }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    render :index
  end

  def show
    @review = Review.find_by(id: params["id"])
    render :show
  end

  def create
    @review = Review.create({
      reservation_id: params["reservation_id"],
      rating: params["rating"],
      comment: params["comment"],
    })

    if @review.save
      redirect_to @review
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @review = Review.find_by(id: params["id"])
    @review.update(
      reservation_id: params["reservation_id"],
      rating: params["rating"],
      comment: params["comment"],
    )

    if @room.valid?
      render :show
    else
      render json: { errors: @review.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find_by(id: params["id"])
    @review.destroy

    render json: { message: "Review Destroyed" }
  end

  private

  def review_params
    params.require(:reservation_id).permit(:rating, :comment)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_admin, except: [:index, :show, :home]

  def home
    @rooms = Room.all
    render "rooms/home"
  end
  
  def index
    @rooms = Room.all
    render :index
  end

  def show
    @room = Room.find_by(id: params["id"])
    render :show
  end

  def create
    @room = Room.create({
      user_id: params["user_id"],
      planet: params["planet"],
      price: params["price"],
      total_occupancy: params["total_occupancy"],
      total_bedrooms: params["total_bedrooms"],
      total_bathrooms: params["total_bathrooms"],
      home_type: params[" home_type"],
      section: params["section"],
    })

    if @room.valid?
      Room_Image.create(room_id: @room.id, url: params["image_url"])
      render :show
    else
      render json: { errors: @room.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @room = Room.find_by(id: params["id"])
    @room.update(
      user_id: params["user_id"],
      planet: params["planet"],
      price: params["price"],
      total_occupancy: params["total_occupancy"],
      total_bedrooms: params["total_bedrooms"],
      total_bathrooms: params["total_bathrooms"],
      home_type: params[" home_type"],
      section: params["section"],
    )

    if @room.valid?
      render :show
    else
      render json: { errors: @room.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find_by(id: params["id"])
    @room.destroy

    render json: { message: "Room Destruction Completed" }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end
 
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/room_images_helper.rb
module RoomImagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirGnG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
h1>All Reservations</h1>
<% @reservations.each do |room| %>
  <h2><%= reservation.room.planet %></h2>
  <p>User_ID : <%= reservation.user_id %></p>
  <p>Room_ID: <%= reservation.room_id %></p>
  <p>Start Date: <%= reservation.start_date %></p>
  <p>End Date: <%= reservation.end_date %></p>
  <p>Price: <%= reservation.price %></p>
<% end %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= form_with model: @reservation do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :width %>
    <%= form.text_field :width %>
  </div>
  <div>
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/reservations/show.html.erb
<h2><%= @reservation.room.planet %></h2>
  <p>User_ID : <%= @reservation.user_id %></p>
  <p>Room_ID: <%= @reservation.room_id %></p>
  <p>Start Date: <%= @reservation.start_date %></p>
  <p>End Date: <%= @reservation.end_date %></p>
  <p>Price: <%= @reservation.price %></p>

app/views/reviews/index.html.erb
<h1>Check Out Our Reviews</h1>
<% @reviews.each do |review| %>
  <p>Reservation_Id: <%= review.reservation_id %></p>
  <p>Rating: <%= review.rating %></p>
  <p>Comment: <%= review.comment%></p>

  <% end %>
  
  <%= link_to "Write Your Own Review", new_review_path %>

app/views/reviews/new.html.erb
<h1>Write Your Own Review</h1>


<%= form_with model: @review do |form| %>
  <div>
    <%= form.label :reservation_id %><br>
    <%= form.text_field :reservation_id %>
 
  </div>

  <div>
    <%= form.label :rating %><br>
    <%= form.text_area :rating %><br>
  
  </div>

  <div>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %><br>
 
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

 <%= link_to "Back to Home Page", home_path %>

app/views/reviews/show.html.erb
<h1>Review</h1>

  <p>Reservation_Id: <%= @review.reservation_id%></p>
  <p>Rating: <%= @review.rating %></p>
  <p>Comment: <%= @review.comment%></p>
  <%end%>

  <h1>Leave your own review</h1>

app/views/rooms/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
    body {background-color: skyblue;}
    h1   {
      color: black;
      font-family: verdana:
    }
    p    {
      color: hotpink;
    }

    </style>
  
    <title>AirGnG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><%= link_to "Book a Reservation", new_reservation_path %></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Reviews
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"><%= link_to "View all reviews!", reviews_path %></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to "Write your own review!", new_review_path %></a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><%= link_to "Create an Account", signup_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><%= link_to "Already have an account? Login here!", login_path %></a>
            </li>

          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    
    <h1><p class="text-center">Welcome to AirGnG!</h1>
    <h4><p class="text-center">Where vacations are made PERFECT<h4>
    <%@rooms.each do |room|%>
      <div class="card" style="width: 24rem;">
      <div class="container">
      <div class="row">
        <div class="col-4">
          <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <%index = 0%>
                <%room.room_images.each do |image| %>
                  <% is_active = "" %>
                  <% if index == 0 %>
                    <% is_active = "active" %>
                  <%end%>
                  <div class="carousel-item <%= is_active %>">
                      <img src="<%= image.url %>" class="d-block w-100" alt="...">
                    </div>
                  <% index += 1%>
                <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
    </div>
        <div class="card-body">
          <p class="card-text"><%room.planet%></p>
        </div>
      </div>
    <%end%>



  <div class="container">
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/rooms/index.html.erb
<h1>All Rooms</h1>
<% @rooms.each do |room| %>
  <h2><%= room.planet %></h2>
  <p>Location : <%= room.planet %></p>
  <p>Price: <%= room.price %></p>
  <p>Description: <%= room.description %></p>
  <p>Total Occupancy: <%= room.total_occupancy %></p>
  <p>Total Bedrooms: <%= room.total_bedrooms %></p>
  <p>Total Bathrooms: <%= room.total_bathrooms %></p>
  <p>Home Type: <%= room.home_type %></p>
  <p>Section: <%= room.section %></p>
  <img src="<%= room.room_images %>" width="100" />
  <a href="/rooms/<%= room.id %>">More Info...</a>
  <%# <a href="/reservations/new">Book Now...</a> %>

  <h1>New Reservation</h1>
<%= form_with model: @reservation do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.text_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>
  <div>
    <%= form.submit %>
  </div>
  <% end%>
<% end %> 

app/views/rooms/show.html.erb
<h1>Room</h1>
  <h2><%= @room.planet %></h2>
  <p>Location : <%= @room.planet %></p>
  <p>Price: <%= @room.price %></p>
  <p>Description: <%= @room.description %></p>
  <p>Total Occupancy: <%= @room.total_occupancy %></p>
  <p>Total Bedrooms: <%= @room.total_bedrooms %></p>
  <p>Total Bathrooms: <%= @room.total_bathrooms %></p>
  <p>Home Type: <%= @room.home_type %></p>
  <p>Section: <%= @room.section %></p>
  <% @room.room_images.each do |image| %>
  <img src="<%= image.url %>" width="100" />
  <% end %>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>